import {
  NextRequest,
  NextResponse,
} from "next/server";

import crypto from "crypto";
import mongoose from "mongoose";

import {
  connectMongoose,
} from "@/lib/mongodb";

import User from "@/models/User";
import CustomerSession from "@/models/CustomerSession";
import PasswordResetToken from "@/models/PasswordResetToken";

import {
  checkRateLimit,
} from "@/lib/rateLimit";

import {
  getClientIp,
} from "@/lib/requestSecurity";

import {
  isStrongPassword,
  NEW_PASSWORD_MIN_LENGTH,
  NEW_PASSWORD_MAX_LENGTH,
} from "@/lib/validation";

/*
 * ============================================
 * PASSWORD HASHING
 * ============================================
 */

function hashPassword(
  password: string
): string {
  const salt =
    crypto.randomBytes(16);

  const derivedKey =
    crypto.scryptSync(
      password,
      salt,
      64
    );

  return `${salt.toString(
    "hex"
  )}:${derivedKey.toString(
    "hex"
  )}`;
}

/*
 * ============================================
 * POST
 * ============================================
 */

export async function POST(
  request: NextRequest
) {
  try {
    /*
     * ========================================
     * RATE LIMIT
     * ========================================
     */

    const clientIp =
      getClientIp(request);

    const rateLimit =
      await checkRateLimit({
        key:
          `customer-reset-password-ip:${clientIp}`,
        limit: 5,
        windowMs:
          15 * 60 * 1000,
      });

    if (
      !rateLimit.allowed
    ) {
      return NextResponse.json(
        {
          success: false,
          error:
            "Too many password reset attempts. Please try again later.",
        },
        {
          status: 429,
          headers: {
            "Retry-After":
              String(
                rateLimit.retryAfterSeconds
              ),
          },
        }
      );
    }

    /*
     * ========================================
     * READ REQUEST
     * ========================================
     */

    let body: unknown;

    try {
      body =
        await request.json();
    } catch {
      return NextResponse.json(
        {
          success: false,
          error:
            "Invalid request.",
        },
        {
          status: 400,
        }
      );
    }

    if (
      !body ||
      typeof body !==
        "object" ||
      Array.isArray(body)
    ) {
      return NextResponse.json(
        {
          success: false,
          error:
            "Invalid request.",
        },
        {
          status: 400,
        }
      );
    }

    const requestBody =
      body as Record<
        string,
        unknown
      >;

    const token =
      typeof requestBody.token ===
      "string"
        ? requestBody.token.trim()
        : "";

    const password =
      typeof requestBody.password ===
      "string"
        ? requestBody.password
        : "";

    /*
     * ========================================
     * TOKEN VALIDATION
     * ========================================
     */

    if (!token) {
      return NextResponse.json(
        {
          success: false,
          error:
            "Password reset token is required.",
        },
        {
          status: 400,
        }
      );
    }

    /*
     * Tokens generated by the existing
     * system are 64 hexadecimal characters.
     *
     * Keep the validation aligned with the
     * current token-generation mechanism.
     */

    if (
      token.length !== 64 ||
      !/^[a-f0-9]+$/i.test(
        token
      )
    ) {
      return NextResponse.json(
        {
          success: false,
          error:
            "Password reset token is invalid.",
        },
        {
          status: 400,
        }
      );
    }

    /*
     * ========================================
     * PASSWORD VALIDATION
     * ========================================
     */

    if (!password) {
      return NextResponse.json(
        {
          success: false,
          error:
            "Password is required.",
        },
        {
          status: 400,
        }
      );
    }

    if (
      password.length <
      NEW_PASSWORD_MIN_LENGTH
    ) {
      return NextResponse.json(
        {
          success: false,
          error:
            "Password must be at least 10 characters.",
        },
        {
          status: 400,
        }
      );
    }

    if (
      password.length >
      NEW_PASSWORD_MAX_LENGTH
    ) {
      return NextResponse.json(
        {
          success: false,
          error:
            "Password must not exceed 128 characters.",
        },
        {
          status: 400,
        }
      );
    }

    if (
      !isStrongPassword(
        password
      )
    ) {
      return NextResponse.json(
        {
          success: false,
          error:
            "Password must contain at least one uppercase letter, one lowercase letter, one number, and one special character.",
        },
        {
          status: 400,
        }
      );
    }

    /*
     * ========================================
     * DATABASE
     * ========================================
     */

    await connectMongoose();

    /*
     * ========================================
     * HASH PROVIDED TOKEN
     * ========================================
     */

    const tokenHash =
      crypto
        .createHash("sha256")
        .update(token)
        .digest("hex");

    /*
     * ========================================
     * TRANSACTION
     * ========================================
     */

    const session =
      await mongoose.startSession();

    try {
      let resetCompleted =
        false;

      await session.withTransaction(
        async () => {
          /*
           * ==================================
           * ATOMIC TOKEN CONSUMPTION
           * ==================================
           */

          const resetToken =
            await PasswordResetToken.findOneAndUpdate(
              {
                tokenHash,

                used: false,

                expiresAt: {
                  $gt: new Date(),
                },
              },
              {
                $set: {
                  used: true,
                },
              },
              {
                returnDocument:
                  "after",
                session,
              }
            );

          if (!resetToken) {
            throw new Error(
              "INVALID_RESET_TOKEN"
            );
          }

          /*
           * ==================================
           * FIND CUSTOMER
           * ==================================
           */

          const user =
            await User.findOne({
              _id:
                resetToken.userId,

              role: "customer",
            }).session(
              session
            );

          if (!user) {
            throw new Error(
              "RESET_ACCOUNT_NOT_FOUND"
            );
          }

          /*
           * ==================================
           * UPDATE PASSWORD
           * ==================================
           */

          user.passwordHash =
            hashPassword(
              password
            );

          await user.save({
            session,
          });

          /*
           * ==================================
           * REVOKE OLD SESSIONS
           * ==================================
           */

          await CustomerSession.updateMany(
            {
              userId:
                user._id,

              revokedAt: null,
            },
            {
              $set: {
                revokedAt:
                  new Date(),
              },
            },
            {
              session,
            }
          );

          resetCompleted =
            true;
        }
      );

      if (
        !resetCompleted
      ) {
        return NextResponse.json(
          {
            success: false,
            error:
              "Unable to reset your password.",
          },
          {
            status: 500,
          }
        );
      }

      return NextResponse.json({
        success: true,
        message:
          "Your password has been reset successfully. Please log in again.",
      });
    } catch (error) {
      if (
        error instanceof Error &&
        error.message ===
          "INVALID_RESET_TOKEN"
      ) {
        return NextResponse.json(
          {
            success: false,
            error:
              "This password reset link is invalid or has expired.",
          },
          {
            status: 400,
          }
        );
      }

      if (
        error instanceof Error &&
        error.message ===
          "RESET_ACCOUNT_NOT_FOUND"
      ) {
        return NextResponse.json(
          {
            success: false,
            error:
              "Unable to reset this account.",
          },
          {
            status: 400,
          }
        );
      }

      console.error(
        "RESET PASSWORD REQUEST FAILED"
      );

      return NextResponse.json(
        {
          success: false,
          error:
            "Unable to reset your password.",
        },
        {
          status: 500,
        }
      );
    } finally {
      await session.endSession();
    }
  } catch {
    console.error(
      "RESET PASSWORD ENDPOINT FAILED"
    );

    return NextResponse.json(
      {
        success: false,
        error:
          "Unable to reset your password.",
      },
      {
        status: 500,
      }
    );
  }
}